// The demo's payload is generated by the product's own harvester (see
// demo/data/build.mjs), so there is nothing here that re-checks the derivation — that
// would be the second implementation this repo just finished deleting.
//
// What is checked instead is what *this* repo is on the hook for: that the committed
// output is internally consistent and actually loadable by the board. Deliberately no
// list of expected fields: a hand-kept list of what the harvester produces is the same
// mistake in a new place, and it would go stale the first time a field is added.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const load = async (f) => JSON.parse(await readFile(path.join(ROOT, "demo/data", f), "utf8"));

test("roadmap.json parses and its own counts agree with its items", async () => {
  const j = await load("roadmap.json");
  assert.ok(Array.isArray(j.items) && j.items.length > 0, "no items");
  assert.equal(j.total, j.items.length, "total disagrees with items");

  const seen = {};
  for (const i of j.items) seen[i.status] = (seen[i.status] || 0) + 1;
  for (const s of j.statuses) {
    assert.equal(j.counts[s] ?? 0, seen[s] ?? 0, `counts.${s} disagrees with the items`);
  }
  assert.deepEqual(
    Object.keys(seen).filter((s) => !j.statuses.includes(s)),
    [],
    "an item carries a status the payload does not list",
  );
});

test("every source's count matches the items attributed to it", async () => {
  const j = await load("roadmap.json");
  assert.ok(j.sources.length > 0, "no sources");
  for (const s of j.sources) {
    const n = j.items.filter((i) => i.repo === s.repo).length;
    assert.equal(s.count, n, `${s.repo}: source says ${s.count}, items say ${n}`);
    assert.equal(s.error, null, `${s.repo} harvested with an error`);
  }
});

test("the relations resolve inside the payload", async () => {
  // parent/children/blockedBy are ids into this same file. A dangling one means the
  // fixture and the build disagree, which is exactly the drift this data used to have.
  const j = await load("roadmap.json");
  const ids = new Set(j.items.map((i) => i.id));
  for (const i of j.items) {
    if (i.parentRef) assert.ok(ids.has(i.parentRef), `${i.id}: parent ${i.parentRef} missing`);
    for (const c of i.children) assert.ok(ids.has(c), `${i.id}: child ${c} missing`);
    if (i.progress) assert.equal(i.progress.total, i.children.length, `${i.id}: rollup total`);
  }
});

test("the demo still shows what the landing page sells", async () => {
  // Not a feature inventory — three claims the site makes in prose, each of which was
  // false on the board at some point while the fixture was maintained by hand.
  const j = await load("roadmap.json");
  const some = (f) => j.items.filter(f).length;
  assert.ok(some((i) => i.children.length > 0) > 0, "no etapp: the Etapps view is empty");
  assert.ok(some((i) => i.agent) > 0, "no agent: §04 routes to a specialist nobody has");
  assert.ok(some((i) => i.signals.length) > 0, "no signals: Needs attention is empty");
});

test("roadmap.js carries the same payload the board reads from file://", async () => {
  const json = await load("roadmap.json");
  const js = await readFile(path.join(ROOT, "demo/data/roadmap.js"), "utf8");
  const m = /window\.__ROADMAP__ = ([\s\S]+);\s*$/.exec(js);
  assert.ok(m, "roadmap.js does not assign window.__ROADMAP__");
  assert.deepEqual(JSON.parse(m[1]), json, "the two generated files disagree");
});
